from bs4 import BeautifulSoup
from typing import Dict, Any, List, Optional, Set
import re
from urllib.parse import urlparse
import logging
import json
import hashlib
import trafilatura
from readability import Document
import os
from datetime import datetime

logger = logging.getLogger(__name__)


class ContentProcessor:
    """
    ONE AND ONLY HTML extraction stage.
    
    Responsibilities:
    - Remove non-content tags (script, style, iframe, svg)
    - Remove pure junk patterns (cookie notices, nav text, footer boilerplate)
    - Extract ALL other content (no length-based filtering)
    - Preserve structure (headings, sections, tables, lists, cards)
    
    Does NOT:
    - Filter by length (keep "Price: $99", "Status: Active")
    - Remove content based on DOM heuristics
    - Apply chunking logic
    """
    
    # Tags with NO visible content - safe to remove
    NON_CONTENT_TAGS = {
        'script', 'style', 'noscript', 'iframe', 'svg',
        'meta', 'link', 'head', 'template'
    }

    # ✅ Minimum junk patterns - only clear boilerplate
    JUNK_PATTERNS = [
        r'^©.*all rights reserved$',
        r'^cookie policy$',
        r'^privacy policy$',
        r'^terms of service$',
        r'^terms and conditions$',
        r'^accept cookies$',
        r'^we use cookies',
        r'^subscribe to our newsletter',
        r'^follow us on',
        r'^share this post',
        r'^leave a comment',
        r'^your email address',
        r'^search this site',
        r'^powered by wordpress',
        r'^powered by',
        r'^generated by',
        r'^back to top$',
        r'^loading',
        r'^please wait',
        r'^advertisement',
        r'^sponsored',
        r'^promoted',
        r'^sign up for',
        r'^join our newsletter',
        r'^download our app',
        r'^\{\{.*\}\}$',  # Template placeholders
        r'^\[.*\]$',       # Empty brackets
    ]

    # Debug logging
    DEBUG_ENABLED = True
    DEBUG_LOG_PATH = "/app/debug_content_processing.log"
    
    @classmethod
    def _debug_log(cls, message: str, data: Any = None):
        """Write debug information to a log file."""
        if not cls.DEBUG_ENABLED:
            return
        
        timestamp = datetime.now().isoformat()
        log_entry = f"\n{'='*80}\n[{timestamp}] {message}\n"
        
        if data is not None:
            if isinstance(data, str):
                log_entry += data
            elif isinstance(data, dict) or isinstance(data, list):
                try:
                    log_entry += json.dumps(data, indent=2, default=str)
                except:
                    log_entry += str(data)
            else:
                log_entry += str(data)
        
        log_entry += f"\n{'='*80}\n"
        
        try:
            with open(cls.DEBUG_LOG_PATH, 'a', encoding='utf-8') as f:
                f.write(log_entry)
        except Exception as e:
            logger.error(f"Failed to write debug log: {e}")
        
        # Also log to console
        logger.debug(log_entry[:500] + "..." if len(log_entry) > 500 else log_entry)

    @staticmethod
    def _is_junk(text: str) -> bool:
        """Check if text is clear junk/boilerplate."""
        if not text:
            return True
        cleaned = text.strip().lower()
        if not cleaned:
            return True
        # Single characters are junk
        if len(cleaned) <= 1:
            return True
        # Check patterns
        for pattern in ContentProcessor.JUNK_PATTERNS:
            if re.search(pattern, cleaned, re.IGNORECASE):
                return True
        return False

    @staticmethod
    def _count_cards(soup: BeautifulSoup) -> int:
        """Count product/item cards OR any generic repeated data containers."""
        card_selectors = [
            '[data-product]', '[data-item]', '[data-model]',
            '.product-card', '.item-card', '.pd-item',
            '.product-item', '[class*="product-card"]',
            '[class*="item-card"]', '[class*="grid-item"]'
        ]
        for selector in card_selectors:
            found = soup.select(selector)
            if len(found) > 2:
                logger.debug(f"🃏 Card selector '{selector}' matched {len(found)} elements")
                return len(found)

        # Generic repeated container detection
        from collections import Counter
        class_counts = Counter()
        for el in soup.find_all(['div', 'li', 'article', 'section', 'tr'], class_=True):
            for cls in el.get('class', []):
                if cls in {'col', 'row', 'container', 'wrapper', 'flex', 'grid',
                        'active', 'hidden', 'clearfix', 'pull-left', 'pull-right'}:
                    continue
                if len(cls) < 3:
                    continue
                if len(el.get_text(strip=True)) > 20:
                    class_counts[cls] += 1

        if class_counts:
            top_class, top_count = class_counts.most_common(1)[0]
            if top_count >= 5:
                logger.debug(f"🃏 Generic repeated container detected: '.{top_class}' × {top_count}'")
                return top_count

        return 0

    @classmethod
    def _classify_page_type(cls, url: str, soup: BeautifulSoup) -> str:
        path = urlparse(url).path.lower()
        logger.debug(f"🔍 Classifying page type for path: '{path}'")

        listing_url_signals = [
            '/all-', '/explore-', '/shop/', '/category/',
            '/products/', '/collection/', '/search',
            '/smartphones', '/tablets', '/tvs', '/monitors',
            '/appliances', '/watches', '/earbuds',
            '/pages/', '/list', '/index', '/browse',
            '/directory', '/catalog', '/items', '/entries',
        ]

        detail_url_signals = [
            '/buy', r'-sm-[a-z]\d+', r'/[a-z]+-\d{3,}',
            '/detail', '/product/', '/item/',
            '/p/', '/dp/'
        ]

        for signal in listing_url_signals:
            if signal in path:
                card_count = cls._count_cards(soup)
                logger.debug(f"🔍 Listing URL signal '{signal}' matched — card count: {card_count}")
                if card_count > 2:
                    logger.info(f"📋 Page classified as LISTING (signal='{signal}', cards={card_count})")
                    return 'listing'

        for signal in detail_url_signals:
            if re.search(signal, path, re.I):
                logger.info(f"🔎 Page classified as DETAIL (signal='{signal}')")
                return 'detail'

        card_count = cls._count_cards(soup)
        if card_count > 4:
            logger.info(f"📋 Page classified as LISTING via DOM only (cards={card_count})")
            return 'listing'

        logger.info(f"📰 Page classified as ARTICLE (default, no matching signals, cards={card_count})")
        return 'article'
    
    @classmethod
    def _extract_cards(cls, soup: BeautifulSoup, url: str, page_title: str) -> List[Dict]:
        """
        Extract cards from listing pages.
        PRESERVES ALL cards - even without names.
        """
        cls._debug_log(f"🃏 EXTRACT_CARDS START", {
            'url': url,
            'page_title': page_title
        })
        
        from collections import Counter

        card_selectors = [
            '[data-product]', '[data-item]', '[data-model]',
            '.product-card', '.item-card', '.pd-item',
            '.product-item', '[class*="product-card"]',
            '[class*="item-card"]', 'li.product', 'div.product'
        ]

        card_elements = []
        matched_selector = None
        for selector in card_selectors:
            found = soup.select(selector)
            if len(found) > 2:
                card_elements = found
                matched_selector = selector
                break

        if not card_elements:
            class_counts = Counter()
            candidates = {}
            for el in soup.find_all(['div', 'li', 'article', 'section'], class_=True):
                for class_name in el.get('class', []):
                    if class_name in {'col', 'row', 'container', 'wrapper', 'flex', 'grid',
                            'active', 'hidden', 'clearfix', 'pull-left', 'pull-right'}:
                        continue
                    if len(class_name) < 3:
                        continue
                    if len(el.get_text(strip=True)) > 20:
                        class_counts[class_name] += 1
                        if class_name not in candidates:
                            candidates[class_name] = []
                        candidates[class_name].append(el)

            if class_counts:
                top_class, top_count = class_counts.most_common(1)[0]
                if top_count >= 5:
                    card_elements = candidates[top_class]
                    matched_selector = f'.{top_class} (auto-detected)'
                    logger.info(f"🃏 Auto-detected card container: '.{top_class}' × {top_count}'")

        if not card_elements:
            logger.warning(f"🃏 No card elements found for listing page: {url}")
            return []

        sections = []
        seen_names = set()
        total_kept = 0
        skipped_junk = 0

        for i, card in enumerate(card_elements):
            # Try to get a name, but don't skip cards without one
            name_el = (
                card.select_one('h1, h2, h3, h4, h5, h6') or
                card.select_one('[class*="title"], [class*="name"], [class*="model"]') or
                card.select_one('a')
            )

            name = name_el.get_text(strip=True) if name_el else ''

            # If no name, use first line of text or "Card {i}"
            if not name:
                lines = [l.strip() for l in card.get_text('\n', strip=True).split('\n') if l.strip()]
                name = lines[0] if lines else f"Card {i+1}"

            # Handle duplicates with variants
            base_name = name
            counter = 1
            while name.lower() in seen_names:
                name = f"{base_name} {counter}"
                counter += 1
            seen_names.add(name.lower())

            card_text = card.get_text(' ', strip=True)
            
            price_el = card.select_one('[class*="price"], [data-price], .price')
            desc_el = card.select_one('[class*="desc"], [class*="summary"], p')
            link_el = card.select_one('a[href]')

            price = price_el.get_text(strip=True) if price_el else ''
            desc = desc_el.get_text(strip=True) if desc_el else ''
            href = link_el.get('href', '') if link_el else ''

            # Build content - preserve ALL available information
            if price or (desc and desc != name):
                content_parts = [f"Name: {name}"]
                if price:
                    content_parts.append(f"Price: {price}")
                if desc and desc.lower() != name.lower():
                    content_parts.append(f"Description: {desc}")
                if href:
                    full_url = href if href.startswith('http') else \
                        f"{urlparse(url).scheme}://{urlparse(url).netloc}{href}"
                    content_parts.append(f"URL: {full_url}")
                # Add any additional text that wasn't captured
                card_text_without_fields = card_text
                for part in content_parts[1:]:
                    card_text_without_fields = card_text_without_fields.replace(part.split(':', 1)[-1].strip(), '').strip()
                if card_text_without_fields and len(card_text_without_fields) > 10:
                    content_parts.append(f"Details: {card_text_without_fields}")
                content = '\n'.join(content_parts)
            else:
                # Use ALL card text
                content = card_text
                if href:
                    full_url = href if href.startswith('http') else \
                        f"{urlparse(url).scheme}://{urlparse(url).netloc}{href}"
                    content += f"\nURL: {full_url}"

            # Check if junk
            is_junk = ContentProcessor._is_junk(content)
            
            if is_junk:
                skipped_junk += 1
                cls._debug_log(f"🃏 SKIPPED JUNK CARD #{i}", {
                    'name': name,
                    'content_preview': content[:200] + "..." if len(content) > 200 else content
                })
                continue

            sections.append({
                'heading': name,
                'heading_path': [page_title, name],
                'content': f"[{page_title} > {name}]\n\n{content}",
                'source_url': href or url,
                'chunk_category': 'main_content',
                'page_type': 'card'
            })
            total_kept += 1

        cls._debug_log(f"🃏 EXTRACT_CARDS RESULT", {
            'total_cards': len(card_elements),
            'kept': total_kept,
            'skipped_junk': skipped_junk
        })
        
        logger.info(f"🃏 Card extraction: {total_kept} cards kept, {skipped_junk} junk skipped")
        return sections

    @classmethod
    def _extract_article_content(cls, html: str, url: str, page_title: str) -> List[Dict]:
        """
        Extract content using multiple strategies with graceful fallback.
        PRESERVES ALL content - no length-based filtering.
        """
        cls._debug_log(f"📰 EXTRACT_ARTICLE_CONTENT START", {
            'url': url,
            'page_title': page_title,
            'html_length': len(html)
        })
        
        logger.debug(f"📰 Starting article extraction for: {url} (html length: {len(html)} chars)")
        
        content = None
        extraction_method = None
        
        # Strategy 1: Trafilatura
        try:
            content = trafilatura.extract(
                html,
                url=url,
                include_tables=True,
                include_comments=False,
                include_formatting=True,
                favor_recall=True,
                no_fallback=False
            )
            if content:
                extraction_method = "Trafilatura"
                cls._debug_log(f"✅ Trafilatura extracted", {
                    'length': len(content),
                    'word_count': len(content.split()),
                    'preview': content[:500] + "..." if len(content) > 500 else content
                })
                logger.debug(f"✅ Trafilatura extracted {len(content)} chars from {url}")
                # Don't discard based on length - even short content is valuable
        except Exception as e:
            logger.warning(f"⚠️ Trafilatura failed for {url}: {e}")
            content = None
        
        # Strategy 2: Readability
        if not content:
            logger.info(f"🔄 Trying Readability fallback for {url}")
            try:
                doc = Document(html)
                readable_html = doc.summary()
                readable_text = BeautifulSoup(
                    readable_html, 'html.parser'
                ).get_text(separator='\n', strip=True)
                
                if readable_text:
                    content = readable_text
                    extraction_method = "Readability"
                    cls._debug_log(f"✅ Readability fallback succeeded", {
                        'length': len(content),
                        'word_count': len(content.split()),
                        'preview': content[:500] + "..." if len(content) > 500 else content
                    })
                    logger.info(f"✅ Readability fallback succeeded: {len(content)} chars for {url}")
            except Exception as e:
                logger.warning(f"❌ Readability fallback raised exception for {url}: {e}")
        
        # Strategy 3: DOM-based extraction
        if not content:
            logger.info(f"🔄 Trying DOM-based extraction fallback for {url}")
            content = cls._extract_content_from_dom(html, url)
            if content:
                extraction_method = "DOM-based"
                cls._debug_log(f"✅ DOM extraction succeeded", {
                    'length': len(content),
                    'word_count': len(content.split()),
                    'preview': content[:500] + "..." if len(content) > 500 else content
                })
                logger.info(f"✅ DOM extraction succeeded: {len(content)} chars for {url}")
        
        # Strategy 4: Basic text extraction (last resort)
        if not content:
            logger.info(f"🔄 Trying basic text extraction for {url}")
            soup = BeautifulSoup(html, 'html.parser')
            for tag in soup(['script', 'style', 'noscript', 'iframe', 'svg']):
                tag.decompose()
            content = soup.get_text(separator='\n\n', strip=True)
            if content:
                extraction_method = "Basic text"
                cls._debug_log(f"✅ Basic text extraction succeeded", {
                    'length': len(content),
                    'word_count': len(content.split()),
                    'preview': content[:500] + "..." if len(content) > 500 else content
                })
                logger.info(f"✅ Basic text extraction: {len(content)} chars for {url}")
        
        # If we have ANY content, use it - no length filtering
        if not content:
            logger.warning(f"🚫 No content at all for {url}")
            cls._debug_log(f"❌ NO CONTENT EXTRACTED", {
                'url': url,
                'html_length': len(html)
            })
            return []
        
        cls._debug_log(f"📰 EXTRACT_ARTICLE_CONTENT RESULT", {
            'method': extraction_method,
            'original_html_length': len(html),
            'extracted_length': len(content),
            'word_count': len(content.split())
        })
        
        # Clean up whitespace
        content = re.sub(r'\n{3,}', '\n\n', content)
        content = re.sub(r'[ \t]+', ' ', content)
        
        # Split into sections - this will preserve everything
        sections = cls._split_into_sections(content, page_title, url)
        logger.debug(f"✂️ Split into {len(sections)} sections for {url}")
        return sections

    @classmethod
    def _extract_content_from_dom(cls, html: str, url: str) -> Optional[str]:
        """
        DOM-based content extraction for JS-heavy pages.
        Looks for main content containers and extracts ALL text.
        """
        try:
            soup = BeautifulSoup(html, 'html.parser')
            
            # Remove non-content tags
            for tag in soup(['script', 'style', 'noscript', 'iframe', 'svg']):
                tag.decompose()
            
            # Try common content containers
            content_selectors = [
                'main', 'article', '.content', '.main-content',
                '.post-content', '.article-content', '.entry-content',
                '.markdown-body', '.documentation', '.docs-content',
                '[role="main"]', '#content', '#main-content',
                '.prose', '.text-content', '.body-content',
                '.learning-content', '.page-content'
            ]
            
            content_parts = []
            for selector in content_selectors:
                elements = soup.select(selector)
                if elements:
                    for el in elements:
                        text = el.get_text(separator='\n\n', strip=True)
                        # Don't filter by length - keep everything
                        if text:
                            content_parts.append(text)
            
            if content_parts:
                return '\n\n'.join(content_parts)
            
            # If no main content container found, get ALL visible text
            # This preserves everything on the page
            text = soup.get_text(separator='\n\n', strip=True)
            if text:
                return text
            
            return None
            
        except Exception as e:
            logger.warning(f"DOM extraction failed for {url}: {e}")
            return None

    @classmethod
    def _split_into_sections(cls, content: str, page_title: str, url: str) -> List[Dict]:
        """
        Split extracted text into sections using heading detection.
        PRESERVES ALL content - no length-based filtering.
        Only filters clear junk patterns.
        """
        cls._debug_log(f"✂️ SPLIT_INTO_SECTIONS START", {
            'content_length': len(content),
            'word_count': len(content.split()),
            'page_title': page_title,
            'url': url
        })
        
        sections = []
        current_heading = page_title
        heading_path = [page_title]
        current_content = []
        seen_hashes = set()
        headings_found = 0
        junk_skipped = 0
        
        def flush():
            nonlocal current_content
            if not current_content:
                return
            text = '\n\n'.join(current_content).strip()
            # Only filter junk, NEVER filter by length
            if ContentProcessor._is_junk(text):
                nonlocal junk_skipped
                junk_skipped += 1
                cls._debug_log(f"✂️ FLUSH: JUNK SKIPPED", {
                    'text_preview': text[:200] + "..." if len(text) > 200 else text
                })
                current_content = []
                return
            # Deduplication (keep this - it's good)
            h = hashlib.md5(text.encode()).hexdigest()
            if h in seen_hashes:
                current_content = []
                return
            seen_hashes.add(h)
            path = list(dict.fromkeys(heading_path))
            sections.append({
                'heading': current_heading,
                'heading_path': path,
                'content': f"[{' > '.join(path)}]\n\n{text}",
                'source_url': url,
                'chunk_category': 'main_content'
            })
            current_content = []
        
        lines = content.split('\n')
        total_lines = len(lines)
        empty_lines = 0
        
        for line in lines:
            stripped = line.strip()
            if not stripped:
                empty_lines += 1
                continue
            
            # Trafilatura uses markdown headings
            heading_match = re.match(r'^(#{1,6})\s+(.+)$', stripped)
            if heading_match:
                flush()
                level = len(heading_match.group(1))
                text = heading_match.group(2).strip()
                headings_found += 1
                current_heading = text
                heading_path = heading_path[:level]
                if not heading_path or heading_path[-1] != text:
                    heading_path.append(text)
                continue
            
            current_content.append(stripped)
        
        flush()
        
        # If no sections created (no headings found), split by paragraph blocks
        # PRESERVE ALL - no length filtering
        if not sections and content.strip():
            paragraphs = content.split('\n\n')
            seen_hashes = set()
            para_junk = 0
            for para in paragraphs:
                para = para.strip()
                if not para or cls._is_junk(para):
                    para_junk += 1
                    continue
                h = hashlib.md5(para.encode()).hexdigest()
                if h in seen_hashes:
                    continue
                seen_hashes.add(h)
                sections.append({
                    'heading': page_title,
                    'heading_path': [page_title],
                    'content': f"[{page_title}]\n\n{para}",
                    'source_url': url,
                    'chunk_category': 'main_content'
                })
            cls._debug_log(f"✂️ FALLBACK: Paragraph splitting", {
                'total_paragraphs': len(paragraphs),
                'junk_skipped': para_junk,
                'sections_created': len(sections)
            })
        
        cls._debug_log(f"✂️ SPLIT_INTO_SECTIONS RESULT", {
            'total_lines': total_lines,
            'empty_lines': empty_lines,
            'headings_found': headings_found,
            'junk_skipped': junk_skipped,
            'sections_created': len(sections),
            'sample_section': sections[0] if sections else None
        })
        
        logger.info(f"✂️ Split into {len(sections)} sections (preserved all content)")
        return sections

    @staticmethod
    def _resolve_title(soup: BeautifulSoup, page_title: Optional[str], source_url: Optional[str]) -> str:
        """Resolve the best available page title from multiple sources."""
        if page_title and page_title.strip():
            return page_title.strip()
        title_tag = soup.find('title')
        if title_tag:
            text = title_tag.get_text(strip=True)
            if text:
                return text
        h1 = soup.find('h1')
        if h1:
            text = h1.get_text(strip=True)
            if text:
                return text
        og_title = soup.find('meta', property='og:title')
        if og_title:
            text = og_title.get('content', '').strip()
            if text:
                return text
        return source_url or 'Untitled Page'

    @staticmethod
    def _extract_metadata(soup: BeautifulSoup, url: str) -> Dict[str, Any]:
        """Extract metadata from meta tags."""
        metadata = {
            'url': url,
            'domain': urlparse(url).netloc if url else '',
            'path': urlparse(url).path if url else '',
            'title': None,
            'description': None,
            'og_title': None,
            'og_description': None
        }
        
        title_tag = soup.find('title')
        if title_tag:
            metadata['title'] = title_tag.get_text(strip=True)
        
        meta_desc = soup.find('meta', attrs={'name': 'description'})
        if meta_desc:
            metadata['description'] = meta_desc.get('content', '').strip()
        
        og_title = soup.find('meta', property='og:title')
        if og_title:
            metadata['og_title'] = og_title.get('content', '').strip()
        
        og_desc = soup.find('meta', property='og:description')
        if og_desc:
            metadata['og_description'] = og_desc.get('content', '').strip()
        
        return metadata

    @staticmethod
    def _empty_result(page_title: Optional[str], source_url: Optional[str]) -> Dict[str, Any]:
        """Return empty result structure."""
        title = page_title or 'Untitled'
        return {
            'page_title': title,
            'source_url': source_url or '',
            'page_type': 'empty',
            'main_content': {
                'all_text': '',
                'sections': [],
                'headings': [],
                'paragraphs': [],
                'lists': [],
                'tables': [],
                'has_content': False
            },
            'ui_summary': [],
            'ui_regions': {},
            'metadata': {'url': source_url or ''},
            'document_structure': {
                'page_title': title,
                'source_url': source_url or '',
                'sections': [],
                'tables': [],
                'cards': [],
                'paragraphs': [],
            },
            'is_first_page': False,
            'has_content': False,
            'text_stats': {
                'total_chars': 0,
                'total_words': 0,
                'section_count': 0,
            }
        }

    @classmethod
    def process_html(
        cls,
        html: str,
        source_url: Optional[str] = None,
        page_title: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Universal content extraction.
        
        This is the ONLY HTML cleaning stage.
        Extracts ALL content, only removes true junk.
        """
        # Clear debug log on each run
        try:
            with open(cls.DEBUG_LOG_PATH, 'w', encoding='utf-8') as f:
                f.write(f"=== CONTENT PROCESSING DEBUG LOG ===\n")
                f.write(f"Started: {datetime.now().isoformat()}\n")
                f.write(f"URL: {source_url}\n")
                f.write(f"HTML Length: {len(html)}\n")
                f.write(f"{'='*80}\n\n")
        except:
            pass
        
        cls._debug_log(f"🌐 PROCESS_HTML START", {
            'source_url': source_url,
            'page_title': page_title,
            'html_length': len(html),
            'html_preview': html[:1000] + "..." if len(html) > 1000 else html
        })
        
        if not html:
            logger.error(f"❌ process_html called with empty HTML for url='{source_url}'")
            return cls._empty_result(page_title, source_url)
        
        html_len = len(html)
        logger.info(f"🌐 process_html START: url='{source_url}' | html={html_len} chars")
        
        # STEP 1: Parse HTML
        soup = BeautifulSoup(html, 'html.parser')
        cls._debug_log(f"📄 HTML PARSED", {
            'total_elements': len(soup.find_all(True)),
            'div_count': len(soup.find_all('div')),
            'p_count': len(soup.find_all('p')),
            'heading_count': len(soup.find_all(['h1','h2','h3','h4','h5','h6']))
        })
        
        # STEP 2: Remove non-content tags
        for tag in soup(['script', 'style', 'noscript', 'iframe', 'svg']):
            tag.decompose()
        cls._debug_log(f"🗑️ NON-CONTENT TAGS REMOVED", {
            'removed_tags': ['script', 'style', 'noscript', 'iframe', 'svg'],
            'remaining_text_length': len(soup.get_text())
        })
        
        # Resolve title
        title = cls._resolve_title(soup, page_title, source_url)
        cls._debug_log(f"🏷️ TITLE RESOLVED", {'title': title})
        
        # Classify page type
        page_type = cls._classify_page_type(source_url or '', soup)
        cls._debug_log(f"📋 PAGE CLASSIFIED", {'page_type': page_type})
        logger.info(f"🏷️ Page: title='{title}' | type='{page_type}' | url='{source_url}'")
        
        sections = []
        
        if page_type == 'listing':
            logger.info(f"📋 Running card extraction for listing: {source_url}")
            sections = cls._extract_cards(soup, source_url or '', title)
            
            if not sections:
                logger.warning(f"📋 Listing page but no cards extracted for {source_url} — falling back")
                sections = cls._extract_article_content(html, source_url or '', title)
                page_type = 'article'
            else:
                logger.info(f"📋 Extracted {len(sections)} cards from listing page: {source_url}")
                cls._debug_log(f"📋 CARDS EXTRACTED", {
                    'count': len(sections),
                    'sample': sections[0] if sections else None
                })
        
        else:
            logger.info(f"📰 Running article extraction for {page_type}: {source_url}")
            sections = cls._extract_article_content(html, source_url or '', title)
            if sections:
                logger.info(f"📄 Extracted {len(sections)} sections from {page_type} page: {source_url}")
                cls._debug_log(f"📄 SECTIONS EXTRACTED", {
                    'count': len(sections),
                    'sample': sections[0] if sections else None
                })
            else:
                logger.warning(f"📄 Zero sections extracted from {page_type} page: {source_url}")
        
        has_content = bool(sections)
        
        # Build all_text from sections
        all_text = '\n\n'.join(
            s['content'].split(']\n\n', 1)[-1] if ']\n\n' in s.get('content', '') else s.get('content', '')
            for s in sections
        )
        
        total_words = len(all_text.split())
        cls._debug_log(f"📊 FINAL STATS", {
            'sections_count': len(sections),
            'all_text_length': len(all_text),
            'total_words': total_words,
            'has_content': has_content,
            'page_type': page_type
        })
        
        logger.info(f"🌐 process_html END: url='{source_url}' | sections={len(sections)} | all_text={len(all_text)} chars | words={total_words}")
        
        if not has_content:
            logger.warning(f"🚨 No content produced for '{source_url}'. HTML was {html_len} chars.")
        
        # Build document_structure
        document_structure = {
            'page_title': title,
            'source_url': source_url or '',
            'sections': sections,
            'tables': [],  # Tables are extracted within sections
            'cards': [],   # Cards are extracted as sections
            'paragraphs': [],
        }
        
        metadata = cls._extract_metadata(soup, source_url or '')
        metadata['page_type'] = page_type
        
        result = {
            'page_title': title,
            'source_url': source_url or '',
            'page_type': page_type,
            'main_content': {
                'all_text': all_text,
                'sections': sections,
                'headings': [],
                'paragraphs': [],
                'lists': [],
                'tables': [],
                'has_content': has_content
            },
            'ui_summary': [],
            'ui_regions': {},
            'metadata': metadata,
            'document_structure': document_structure,
            'is_first_page': False,
            'has_content': has_content,
            'text_stats': {
                'total_chars': len(all_text),
                'total_words': len(all_text.split()),
                'section_count': len(sections),
            }
        }
        
        cls._debug_log(f"✅ PROCESS_HTML COMPLETE", {
            'result_keys': list(result.keys()),
            'has_content': has_content,
            'section_count': len(sections),
            'total_chars': len(all_text)
        })
        
        return result

    # ============================================================
    # Legacy methods kept for compatibility
    # ============================================================
    
    @staticmethod
    def clear_boilerplate_cache(domain: Optional[str] = None):
        logger.info(f"🧹 Boilerplate cache is no longer used (domain: {domain})")
    
    @staticmethod
    def get_all_text(html: str) -> str:
        soup = BeautifulSoup(html, 'html.parser')
        for tag in soup(['script', 'style', 'noscript', 'iframe', 'svg']):
            tag.decompose()
        text = soup.get_text(separator='\n', strip=True)
        text = re.sub(r'\n{3,}', '\n\n', text)
        text = re.sub(r'[ \t]+', ' ', text)
        return text
    
    @staticmethod
    def to_markdown(structure: Dict[str, Any]) -> str:
        lines = []
        title = structure.get('page_title', 'Untitled')
        lines.append(f"# {title}\n")
        if structure.get('source_url'):
            lines.append(f"**Source:** {structure['source_url']}\n")
        for section in structure.get('sections', []):
            heading = section.get('heading', '')
            if heading:
                lines.append(f"## {heading}\n")
            lines.append(section.get('content', ''))
            lines.append('')
        if structure.get('all_text') and not structure.get('sections'):
            lines.append("\n")
            lines.append("## Full Content\n")
            lines.append(structure['all_text'])
        return '\n\n'.join(filter(None, lines))